---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kedacore
  namespace: keda
spec:
  interval: 30m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: kedacore
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
