---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-tester
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: wrk
        image: elswork/wrk
        args: ["-t", "4", "-c", "12", "-d", "180", "http://podinfo.app-a:9898"]
      restartPolicy: Never
