---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-creds
  namespace: controllers-system
stringData:
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test