build:
  image:
    name: fluxcd/flux-cli:v2.0.0-rc.5
    entrypoint: [""]
  script:
    - set -x
    - IMAGE_TAG=${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}
    - |
      flux push artifact oci://$CI_REGISTRY_IMAGE:$IMAGE_TAG \
      --creds="$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" \
      --path="./platform" \
      --source="${CI_REPOSITORY_URL}" \
      --revision="${CI_COMMIT_BRANCH}@sha1:${CI_COMMIT_SHA}" \
      --provider=generic
