
test:
  stage: test
  image: 
    name: squidfunk/mkdocs-material
    entrypoint:
      - "/bin/sh"
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: 
    name: squidfunk/mkdocs-material
    entrypoint:
      - "/bin/sh"
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH



build:
  image:
    name: fluxcd/flux-cli:v2.0.0-rc.5
    entrypoint: [""]
  rules:
  - if: '$CI_COMMIT_TAG'
    when: always
  script:
    - set -x
    - |
      flux push artifact oci://$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG \
      --ignore-paths='*,!/platform/**' \
      --creds="$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" \
      --path="." \
      --source="${CI_REPOSITORY_URL}" \
      --revision="${CI_COMMIT_BRANCH}@sha1:${CI_COMMIT_SHA}" \
      --provider=generic  
