build:
  image:
    name: fluxcd/flux-cli:v2.0.0-rc.5
    entrypoint: [""]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - set -x
    - |
      flux push artifact oci://$IMAGE_TAG \
      --creds="$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" \
      --path="./platform" \
      --source="${CI_REPOSITORY_URL}" \
      --revision="${CI_COMMIT_SHORT_SHA}@sha1:${CI_COMMIT_SHA}" \
      --provider=generic
