site_name: FluxCD Demo
site_url: https://nominet.gitlab.io/cyber/architecture-team/fluxcd-demo/ 
site_dir: public
repo_url: https://gitlab.com/nominet/cyber/architecture-team/fluxcd-demo/
repo_name: fluxcd-demo
edit_uri: edit/main/docs/
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/gitlab
  features:
  - content.action.edit
  - navigation.expand
  - content.code.copy
  - navigation.indexes 
  - toc.follow
  - toc.integrate
  - navigation.instant
  - navigation.tracking
  - navigation.top
  - navigation.footer
nav:
- Home: index.md
- Concepts:
  - concepts/index.md
  - GitOps: concepts/gitops.md
  - Kubernetes: concepts/kubernetes.md
  - FluxCD: concepts/fluxcd.md
  - Loose Coupling: concepts/loose-coupling.md
- Implementation:
  - implementation/index.md
  - Git Repositories: implementation/repo-layout.md
  - Change Promotion: implementation/change-promotion.md
  - External Recources: implementation/external-resources.md
- Deployment:
  - deployment/index.md
  - Create: deployment/create.md
  - Destroy: deployment/destroy.md
plugins:
  - search