site_name: Kubernetes SDLC
site_url: https://danielloader.github.io/kubernetes-sdlc/
repo_url: https://github.com/danielloader/kubernetes-sdlc
repo_name: kubernetes-sdlc
edit_uri: edit/main/docs/
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
  - content.action.edit
  - content.code.copy
  - navigation.expand
  - navigation.footer
  - navigation.indexes 
  - navigation.instant
  - navigation.top
  - navigation.tracking
  - toc.follow
  - toc.integrate
nav:
- Home: index.md
- Concepts:
  - concepts/index.md
  - GitOps: concepts/gitops.md
  - Kubernetes: concepts/kubernetes.md
  - FluxCD: concepts/fluxcd.md
  - Loose Coupling: concepts/loose-coupling.md
- Implementation:
  - implementation/index.md
  - Git Repositories: implementation/repo-layout.md
  - Change Promotion: implementation/change-promotion.md
  - External Recources: implementation/external-resources.md
  - Failure States: implementation/failure-states.md
- End to End: end-to-end.md
- Deployment:
  - deployment/index.md
  - Create: deployment/create.md
  - Destroy: deployment/destroy.md