version: "3"

dotenv: ['.env']

vars:
  CLUSTERS:
    sh: echo $(find ./create -type f -iname '*.yaml')

tasks:
  create-clusters:
    cmds:
      - |
        for CLUSTER in {{.CLUSTERS}}
        do 
          NAME=$(yq '.name' < "$CLUSTER")
          kind create cluster --config "$CLUSTER"
          flux bootstrap github --context kind-$NAME --token-auth --owner danielloader --repository fluxcd-demo --path ./clusters/$NAME
        done

  delete-clusters:
    cmds:
      - |
        for CLUSTER in {{.CLUSTERS}}
        do 
          NAME=$(yq '.name' < "$CLUSTER")
          kind delete cluster --name $NAME
        done
