version: "3"

dotenv: ['.env']

tasks:
  bootstrap-staging:
    cmds:
      - kind create cluster --config create/staging.yaml
      - flux bootstrap gitlab --context kind-staging --token-auth --owner nominet/cyber/architecture-team --repository fluxcd-demo --path ./clusters/staging 
  
  bootstrap-production:
    cmds:
      - kind create cluster --config create/staging.yaml
      - flux bootstrap gitlab --context kind-staging --token-auth --owner nominet/cyber/architecture-team --repository fluxcd-demo --path ./clusters/staging 

  create: 
    cmds:
      - task: bootstrap-staging
      - task: bootstrap-production

  delete:
    cmds:
      - kind delete clusters --all