version: "3"

dotenv: ['.env']

vars:
  CLUSTERS:
    sh: echo $(find ./create -type f -iname '*.yaml')

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'
    error_only: false

tasks:
  create-cluster:
    internal: true
    cmds:
    - kind create cluster --config "{{.CLUSTER_CONFIG_PATH}}" --wait 60s
    - kubectl create namespace flux-system
    - kubectl create secret docker-registry platform-repository --docker-server=registry.gitlab.com --docker-username="{{.GITLAB_USERNAME}}" --docker-password="{{.GITLAB_TOKEN}}" --namespace flux-system --context kind-{{.CLUSTER_NAME}}
    - flux bootstrap gitlab --token-auth --owner ***REMOVED***  --repository fluxcd-demo --path "./clusters/{{.CLUSTER_NAME}}" --context kind-{{.CLUSTER_NAME}}
    vars:
      CLUSTER_NAME:
        sh: yq '.name' < "{{.CLUSTER_CONFIG_PATH}}"
    status:
    - kubectl cluster-info --context kind-{{.CLUSTER_NAME}}

  delete-cluster:
    internal: true
    cmds:
    - kind delete cluster --name "{{.CLUSTER_NAME}}"
    vars:
      CLUSTER_NAME:
        sh: yq '.name' < "{{.CLUSTER_CONFIG_PATH}}"

  create:
    deps:
    - task: create-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/production.yaml"
    - task: create-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/staging.yaml"
    - task: create-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/development.yaml"
    cmds:
    - echo "Deployed!"


  delete:
    cmds:
    - task: delete-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/production.yaml"
    - task: delete-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/staging.yaml"
    - task: delete-cluster
      vars: 
        CLUSTER_CONFIG_PATH: "create/development.yaml"
    - echo "Destroyed!"