---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: raw-bucket
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-east-1
    acl: private
    notificationConfiguration:
      queueConfigurations:
        - queueArnRef: 
            name: "raw-bucket-events"
          events:
            - s3:ObjectCreated:*
          filter:
            key:
              filterRules:
                - name: suffix
                  value: .pcap.gz
                - name: prefix
                  value: raw/
  providerConfigRef:
    name: localstack
  writeConnectionSecretToRef:
    name: raw-bucket
---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: raw-bucket-events
spec:
  forProvider:
    region: us-east-1
    delaySeconds: 0
    visibilityTimeout: 600
  providerConfigRef:
    name: localstack
  writeConnectionSecretToRef:
    name: raw-bucket-events
