apiVersion: v1
kind: Namespace
metadata:
  name: localstack
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: localstack
  namespace: localstack
spec:
  interval: 1h
  url: https://localstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localstack
  namespace: pdns
spec:
  interval: 1m
  targetNamespace: localstack
  chart:
    spec:
      chart: localstack
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: lackstack
  values:
    service:
      type: ClusterIP
    extraEnvVars:
      - name: DEBUG
        value: "1"
