apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.chaos-mesh.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: chaos-mesh
  chart:
    spec:
      chart: chaos-mesh
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
