apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 10Gi
  metricReporter:
    enabled: true
  configOverrides:
    server:
      - confluent.balancer.topic.replication.factor=1
      - confluent.durability.topic.replication.factor=1
      - confluent.license.topic.replication.factor=1
      - confluent.tier.metadata.replication.factor=1
      - transaction.state.log.replication.factor=1
      - offsets.topic.replication.factor=1
      - confluent.cluster.link.metadata.topic.replication.factor=1