apiVersion: v1
kind: Namespace
metadata:
  name: confluent-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: confluent
  namespace: flux-system
spec:
  interval: 1h
  url: https://packages.confluent.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: confluent-system
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluent
        namespace: flux-system

