apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kafka
  - ./kafka
patches:
  - path: ./patches/kafka/kafka-patch.yaml
  - path: ./patches/kafka/controlcenter-patch.yaml
  - path: ./patches/kafka/connect-patch.yaml
