# Bit of a bodge has OLM has no published helm charts, but uses helm in their CLI
# This attempts to use their helm charts without needing to bootstrap the cluster with the CLI
# Else you'd have a twin stage bootstrap, once with Flux and once with OLM.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: ">= v0.23.1"
  url: https://github.com/operator-framework/operator-lifecycle-manager.git
  ignore: |
    # exclude all
    /*
    # include chart
    !/deploy/chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./deploy/chart/
      sourceRef:
        kind: GitRepository
        name: olm
        namespace: flux-system
      interval: 1m

