apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: kube-prometheus-stack
spec:
  interval: 1m
  targetNamespace: monitoring
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

---
