apiVersion: v1
kind: Namespace
metadata:
  name: pdns
# ---
### disabled for RAM reasons
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: pdns-elastic
#   namespace: pdns
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   dependsOn:
#     - name: elastic-controller
#       namespace: flux-system
#   path: ./components/services/elastic/
#   targetNamespace: pdns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redpanda
  namespace: pdns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: redpanda-controller
      namespace: flux-system
    - name: cert-manager-system
      namespace: flux-system
  path: ./apps/redpanda
  targetNamespace: pdns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka
  namespace: pdns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: confluent-controller
      namespace: flux-system
  path: ./apps/kafka
  targetNamespace: pdns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pcap-preprocessor
  namespace: pdns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: localstack
      namespace: pdns
  path: ./apps/pcap-preprocessor/
  targetNamespace: pdns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: localstack
  namespace: pdns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: crossplane-controller
      namespace: flux-system
  path: ./infrastructure/system/localstack
  # targetNamespace: pdns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka-emitter
  namespace: pdns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: kafka
      namespace: pdns
  path: ./apps/kafka-emitter/
  targetNamespace: pdns