apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: apps
  patches:
    - patch: |
        - op: replace
          path: /spec/values/replicaCount
          value: 2
      target: 
          kind: HelmRelease
          name: podinfo
