---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: platform
  namespace: flux-system
spec:
  secretRef:
    name: platform-repository
  interval: 1m0s
  url: https://gitlab.com/***REMOVED***/fluxcd-demo.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-services
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/services
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-service-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/service-configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform


