apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example
provisioner: rancher.io/local-path
parameters:
  nodePath: /tmp/example
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
