apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-es-http.elastic.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elastic.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kafka_log
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
      # - name: Kafka on ECK Policy
      #   id: kafka-agent
      #   unenroll_timeout: 900
      #   namespace: default
      #   is_managed: true
      #   package_policies:
      #     - name: dns_kafka
      #       package:
      #         name: kafka_log
      #         # version: 1.0.0
      #       id: kafka
      #       inputs:
      #         - type: kafka_log-kafka
      #           enabled: true
      #           streams:
      #             - enabled: true
      #               data_stream:
      #                 dataset: dns.customer.nominet.uk
      #               vars:
      #                 - name: hosts
      #                   value: [kafka.kafka:9092]
      #                 - name: topics
      #                   value: [tshark.ingress.dns.customer.nominet.uk]
      #                 - name: group_id
      #                   value: dns.customer.nominet.uk
      #                 - name: parsers
      #                   value: |
      #                     - ndjson:
      #                       keys_under_root: true
      #                 - name: ssl
      #                   value: |
      #                     enabled: false
      #                     certificate: "/etc/pki/client/cert.pem"
      #                     key: "/etc/pki/client/cert.key"
      #                 - name: tags
      #                   value: [forwarded]
