
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      verify:
        provider: cosign
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
      version: '>5.0.0'
  interval: 1m0s
  releaseName: podinfo
  values:
    replicaCount: 1