apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-emitter
  namespace: pdns
spec:
  selector:
    matchLabels:
      app: kafka-emitter
  template:
    metadata:
      labels:
        app: kafka-emitter
    spec:
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 10Gi
      containers:
      - name: kafka-emitter
        image: local/kafka-emitter:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2Gi"
        env:
          - name: AWS_ACCESS_KEY_ID
            value: test          
          - name: AWS_SECRET_ACCESS_KEY
            value: test          

