apiVersion: v1
kind: Namespace
metadata:
  name: redpanda-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redpanda
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.vectorized.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: redpanda-system
  chart:
    spec:
      chart: redpanda-operator
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
  # values:
    # monitoring:
    #   enabled: true
    # logging:
    #   logLevel: "debug"
    # storage:
    #   persistentVolume:
    #     enabled: false
    # listeners:
    #   http:
    #     enabled: false
    #   schemaRegistry:
    #     enabled: false