---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: redpanda
spec:
  interval: 5m0s
  url: https://github.com/redpanda-data/redpanda
  ref:
    branch: v22.3.x
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: redpanda
  dependsOn:
    - name: confluent-controller
      namespace: flux-system
  path: ./src/go/k8s/config/crd
