---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: s3
  namespace: kafka
spec:
  class: "io.confluent.connect.s3.source.S3SourceConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    aws.access.key.id: "test"
    aws.secret.access.key: "test"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    mode: "GENERIC"
    s3.bucket.name: "raw-bucket"
    s3.region: "us-east-1"
    store.url: "http://localstack-localstack.localstack:4566"
    task.batch.size: "10"
    topic.regex.list: "tshark.ingress.dns.customer.***REMOVED***.uk:.*"
    topics.dir: "json"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    record.batch.max.size: "10000"
    s3.poll.interval.ms: "10000"
  restartPolicy:
    type: OnFailure
---