apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  postRenderers:
  - kustomize:
      patches:
      # Patch to work on local insecure clusters
      - patch: |-
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --kubelet-insecure-tls
        target:
          version: apps/v1
          kind: Deployment
          name: metrics-server
  values:
    replicas: 1
